namespace Client
{
    partial class FormClient
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.lsvMess = new System.Windows.Forms.ListView();
            this.txtMess = new System.Windows.Forms.TextBox();
            this.btnSend = new System.Windows.Forms.Button();
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.SuspendLayout();
            // 
            // lsvMess
            // 
            this.lsvMess.Location = new System.Drawing.Point(15, 12);
            this.lsvMess.Name = "lsvMess";
            this.lsvMess.Size = new System.Drawing.Size(625, 314);
            this.lsvMess.TabIndex = 0;
            this.lsvMess.UseCompatibleStateImageBehavior = false;
            this.lsvMess.View = System.Windows.Forms.View.List;
            // 
            // txtMess
            // 
            this.txtMess.Location = new System.Drawing.Point(25, 443);
            this.txtMess.Name = "txtMess";
            this.txtMess.Size = new System.Drawing.Size(451, 20);
            this.txtMess.TabIndex = 1;
            // 
            // btnSend
            // 
            this.btnSend.Location = new System.Drawing.Point(511, 406);
            this.btnSend.Name = "btnSend";
            this.btnSend.Size = new System.Drawing.Size(75, 57);
            this.btnSend.TabIndex = 2;
            this.btnSend.Text = "Send";
            this.btnSend.UseVisualStyleBackColor = true;
            this.btnSend.Click += new System.EventHandler(this.btnSend_Click);
            this.btnSend.KeyDown += new System.Windows.Forms.KeyEventHandler(this.btnSend_KeyDown);
           
            // 
            // listBox1
            // 
            this.listBox1.FormattingEnabled = true;
            this.listBox1.Items.AddRange(new object[] {
            "©",
            "®",
            "‼",
            "⁉",
            "™",
            "ℹ",
            "↔",
            "↕",
            "↖",
            "↗",
            "↘",
            "↙",
            "↩",
            "↪",
            "⌚",
            "⌛",
            "⏩",
            "⏪",
            "⏫",
            "⏬",
            "⏰",
            "⏳",
            "Ⓜ",
            "▪",
            "▫",
            "▶",
            "◀",
            "◻",
            "◼",
            "◽",
            "◾",
            "☀",
            "☁",
            "☎",
            "☑",
            "☔",
            "☕",
            "☝",
            "☺",
            "♈",
            "♉",
            "♊",
            "♋",
            "♌",
            "♍",
            "♎",
            "♏",
            "♐",
            "♑",
            "♒",
            "♓",
            "♠",
            "♣",
            "♥",
            "♦",
            "♨",
            "♻",
            "♿",
            "⚓",
            "⚠",
            "⚡",
            "⚪",
            "⚫",
            "⚽",
            "⚾",
            "⛄",
            "⛅",
            "⛎",
            "⛔",
            "⛪",
            "⛲",
            "⛳",
            "⛵",
            "⛺",
            "⛽",
            "✂",
            "✅",
            "✈",
            "✉",
            "✊",
            "✋",
            "✌",
            "2  ✏",
            "✒",
            "✔",
            "✖",
            "✨",
            "✳",
            "✴",
            "❄",
            "❇",
            "❌",
            "❎",
            "❓",
            "❔",
            "❕",
            "❗",
            "❤",
            "➕",
            "➖",
            "➗",
            "➡",
            "➰",
            "⤴",
            "⤵",
            "⬅",
            "⬆",
            "⬇",
            "⬛",
            "⬜",
            "⭐",
            "⭕",
            "〰",
            "〽",
            "㊗",
            "㊙",
            "🀄",
            "🃏",
            "🅰",
            "🅱",
            "🅾",
            "🅿",
            "🆎",
            "🆑",
            "🆒",
            "🆓",
            "🆔",
            "🆕",
            "🆖",
            "🆗",
            "🆘",
            "🆙",
            "🆚",
            "🇨 🇳",
            "🇩 🇪",
            "🇪 🇸",
            "🇫 🇷",
            "🇬 🇧",
            "🇮 🇹",
            "🇯 🇵",
            "🇰 🇷",
            "🇷 🇺",
            "🇺 🇸",
            "🈁",
            "🈂",
            "7121  🈚",
            "6307  🈯",
            "7981  🈲",
            "77  🈳",
            "5408  🈴",
            "680  🈵",
            "6709  🈶",
            "6708  🈷",
            "7533  🈸",
            "5272  🈹",
            "556  🈺",
            "🉐",
            "🉑",
            "🌀",
            "🌁",
            "🌂",
            "🌃",
            "🌄",
            "🌅",
            "🌆",
            "🌇",
            "🌈",
            "🌉",
            "🌊",
            "🌋",
            "🌌",
            "🌏",
            "🌑",
            "🌓",
            "🌔",
            "🌕",
            "🌙",
            "🌛",
            "2  🌟",
            "🌠",
            "🌰",
            "🌱",
            "🌴",
            "🌵",
            "🌷",
            "🌸",
            "🌹",
            "🌺",
            "🌻",
            "🌼",
            "🌽",
            "🌾",
            "🌿",
            "🍀",
            "🍁",
            "🍂",
            "🍃",
            "🍄",
            "🍅",
            "🍆",
            "🍇",
            "🍈",
            "🍉",
            "🍊",
            "🍌",
            "🍍",
            "🍎",
            "🍏",
            "🍑",
            "🍒",
            "🍓",
            "🍔",
            "🍕",
            "🍖",
            "🍗",
            "🍘",
            "🍙",
            "🍚",
            "🍛",
            "🍜",
            "🍝",
            "🍞",
            "🍟",
            "🍠",
            "🍡",
            "🍢",
            "🍣",
            "🍤",
            "🍥",
            "🍦",
            "🍧",
            "🍨",
            "🍩",
            "🍪",
            "🍫",
            "🍬",
            "🍭",
            "🍮",
            "🍯",
            "🍰",
            "🍱",
            "🍲",
            "🍳",
            "🍴",
            "🍵",
            "🍶",
            "🍷",
            "🍸",
            "🍹",
            "🍺",
            "🍻",
            "🎀",
            "🎁",
            "🎂",
            "🎃",
            "🎄",
            "🎅",
            "🎆",
            "🎇",
            "🎈",
            "🎉",
            "🎊",
            "🎋",
            "🎌",
            "🎍",
            "🎎",
            "🎏",
            "🎐",
            "🎑",
            "🎒",
            "🎓",
            "🎠",
            "🎡",
            "🎢",
            "🎣",
            "🎤",
            "🎥",
            "🎦",
            "🎧",
            "🎨",
            "🎩",
            "🎪",
            "🎫",
            "🎬",
            "🎭",
            "🎮",
            "🎯",
            "🎰",
            "8  🎱",
            "🎲",
            "🎳",
            "🎴",
            "🎵",
            "🎶",
            "🎷",
            "🎸",
            "🎹",
            "🎺",
            "🎻",
            "🎼",
            "🎽",
            "🎾",
            "🎿",
            "🏀",
            "🏁",
            "🏂",
            "🏃",
            "🏄",
            "🏆",
            "🏈",
            "🏊",
            "🏠",
            "🏡",
            "🏢",
            "🏣",
            "🏥",
            "🏦",
            "🏧",
            "🏨",
            "🏩",
            "🏪",
            "🏫",
            "🏬",
            "🏭",
            "🏮",
            "🏯",
            "🏰",
            "🐌",
            "🐍",
            "🐎",
            "🐑",
            "🐒",
            "🐔",
            "🐗",
            "🐘",
            "🐙",
            "🐚",
            "🐛",
            "🐜",
            "🐝",
            "🐞",
            "🐟",
            "🐠",
            "🐡",
            "🐢",
            "🐣",
            "🐤",
            "🐥",
            "🐦",
            "🐧",
            "🐨",
            "🐩",
            "🐫",
            "🐬",
            "🐭",
            "🐮",
            "🐯",
            "🐰",
            "🐱",
            "🐲",
            "🐳",
            "🐴",
            "🐵",
            "🐶",
            "🐷",
            "🐸",
            "🐹",
            "🐺",
            "🐻",
            "🐼",
            "🐽",
            "🐾",
            "👀",
            "👂",
            "👃",
            "👄",
            "👅",
            "👆",
            "👇",
            "👈",
            "👉",
            "👊",
            "👋",
            "👌",
            "👍",
            "👎",
            "👏",
            "👐",
            "👑",
            "👒",
            "👓",
            "👔",
            "👕",
            "👖",
            "👗",
            "👘",
            "👙",
            "👚",
            "👛",
            "👜",
            "👝",
            "👞",
            "👟",
            "👠",
            "👡",
            "👢",
            "👣",
            "👤",
            "👦",
            "👧",
            "👨",
            "👩",
            "👪",
            "👫",
            "👮",
            "👯",
            "👰",
            "👱",
            "👲",
            "👳",
            "👴",
            "👵",
            "👶",
            "👷",
            "👸",
            "👹",
            "👺",
            "👻",
            "👼",
            "👽",
            "👾",
            "🤖",
            "👿",
            "💀",
            "💁",
            "💂",
            "💃",
            "💄",
            "💅",
            "💆",
            "💇",
            "💈",
            "💉",
            "💊",
            "💋",
            "💌",
            "💍",
            "💎",
            "💏",
            "💐",
            "💑",
            "💒",
            "💓",
            "💔",
            "💕",
            "💖",
            "💗",
            "💘",
            "💙",
            "💚",
            "💛",
            "💜",
            "💝",
            "💞",
            "💟",
            "💠",
            "💡",
            "💢",
            "💣",
            "💤",
            "💥",
            "💦",
            "💧",
            "💨",
            "💩",
            "💪",
            "💫",
            "💬",
            "💮",
            "💯",
            "💰",
            "💱",
            "💲",
            "💳",
            "💴",
            "💵",
            "💸",
            "💹",
            "💺",
            "💻",
            "💼",
            "💽",
            "💾",
            "💿",
            "📀",
            "📁",
            "📂",
            "📃",
            "📄",
            "📅",
            "📆",
            "📇",
            "📈",
            "📉",
            "📊",
            "📋",
            "📌",
            "📍",
            "📎",
            "📏",
            "📐",
            "📑",
            "📒",
            "📓",
            "📔",
            "📕",
            "📖",
            "📗",
            "📘",
            "📙",
            "📚",
            "📛",
            "📜",
            "📝",
            "📞",
            "📟",
            "📠",
            "📡",
            "📢",
            "📣",
            "📤",
            "📥",
            "📦",
            "📧",
            "📨",
            "📩",
            "📪",
            "📫",
            "📮",
            "📰",
            "📱",
            "📲",
            "📳",
            "📴",
            "📶",
            "📷",
            "📹",
            "📺",
            "📻",
            "📼",
            "🔃",
            "🔊",
            "🔋",
            "🔌",
            "🔍",
            "🔎",
            "🔏",
            "🔐",
            "🔑",
            "🔒",
            "🔓",
            "🔔",
            "🔖",
            "🔗",
            "🔘",
            "🔙",
            "🔚",
            "🔛",
            "🔜",
            "🔝",
            "🔞",
            "🔟",
            "🔠",
            "🔡",
            "🔢",
            "🔣",
            "🔤",
            "🔥",
            "🔦",
            "🔧",
            "🔨",
            "🔩",
            "🔪",
            "🔫",
            "🔮",
            "🔯",
            "🔰",
            "🔱",
            "🔲",
            "🔳",
            "🔴",
            "🔵",
            "🔶",
            "🔷",
            "🔸",
            "🔹",
            "🔺",
            "🔻",
            "🔼",
            "🔽",
            "🕐",
            "🕑",
            "🕒",
            "🕓",
            "🕔",
            "🕕",
            "🕖",
            "🕗",
            "🕘",
            "🕙",
            "🕚",
            "🕛",
            "🗻",
            "🗼",
            "🗽",
            "🗾",
            "🗿",
            "😁",
            "😂",
            "😃",
            "😄",
            "😅",
            "😆",
            "😉",
            "😊",
            "😋",
            "😌",
            "😍",
            "😏",
            "😒",
            "😓",
            "😔",
            "😖",
            "😘",
            "😚",
            "😜",
            "😝",
            "😞",
            "😠",
            "😡",
            "😢",
            "😣",
            "😤",
            "😥",
            "😨",
            "😩",
            "😪",
            "😫",
            "😭",
            "😰",
            "😱",
            "😲",
            "😳",
            "😵",
            "😷",
            "😸",
            "😹",
            "😺",
            "😻",
            "😼",
            "😽",
            "😾",
            "😿",
            "🙀",
            "🙅",
            "🙆",
            "🙇",
            "🙈",
            "🙉",
            "🙊",
            "🙋",
            "🙌",
            "🙍",
            "🙎",
            "🙏",
            "🚀",
            "🚃",
            "🚄",
            "🚅",
            "🚇",
            "🚉",
            "🚌",
            "🚏",
            "🚑",
            "🚒",
            "🚓",
            "🚕",
            "🚗",
            "🚙",
            "🚚",
            "🚢",
            ""});
            this.listBox1.Location = new System.Drawing.Point(15, 332);
            this.listBox1.MultiColumn = true;
            this.listBox1.Name = "listBox1";
            this.listBox1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.listBox1.Size = new System.Drawing.Size(254, 95);
            this.listBox1.TabIndex = 3;
            this.listBox1.DoubleClick += new System.EventHandler(this.listBox1_DoubleClick);
            // 
            // FormClient
            // 
            this.AcceptButton = this.btnSend;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(652, 475);
            this.Controls.Add(this.listBox1);
            this.Controls.Add(this.btnSend);
            this.Controls.Add(this.txtMess);
            this.Controls.Add(this.lsvMess);
            this.Name = "FormClient";
            this.Load += new System.EventHandler(this.FormClient_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ListView lsvMess;
        private System.Windows.Forms.TextBox txtMess;
        private System.Windows.Forms.Button btnSend;
        private System.Windows.Forms.ListBox listBox1;
    }
}

